install:
- sudo apt-get install texlive-fonts-recommended
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-publishers

script:
- source ./compile.sh

notifications:
- email: false
